### ISSUE TITLE
Verify Page Query Parameter is a number

### ISSUE THREAD

**Issue by confused-Techie** [confused-Techie/atom-community-server-backend-JS#1]
In the below code, verify that the 'prov' or provided value, is in fact a valid number, returning either as a string or integer.
Then feel free to remove the 'TODO'

https://github.com/confused-Techie/atom-community-server-backend-JS/blob/156ed2c85aed5f73717d945425a39a0357c9a606/src/query.js#L9-L21

**Comment by Digitalone1** [comment]
On my website I would generally use [parseInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt).

But this kind of javascript is very new to me, I don't even know if methods of the browsers window object are available, neither I know a way to test it.

If `prov` is not undefined, I'd parse it with parseInt and if the result is not `NaN`, I return the number.

```js
function page(req) {
  let def = 1;
  let prov = req.query.page;

  if (prov === undefined) {
    return def;
  }

  let num = parseInt(prov, 10);

  return (isNaN(num)) ? def : num; 
}
```

If parseInt is not an option, we could cast the value in a string and use a regex [match](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match) to make sure it's a number.

Something like

```js
function page(req) {
  let def = 1;

  if (req.query.page === undefined) {
    return def;
  }

  let prov = `${req.query.page}`;

  return (prov.match(/^\d+$/) !== null) ? prov : def;
}
```

If we are sure the parameter is string or undefined, the cast is even unneded.

Some questions. Why `"undefined"`? I just use `undefined`, it's a primitive type in javascript, don't need to wrap in a string. 

Why `let` is not used for local variables?

**Comment by Digitalone1** [comment]
We had a misunderstanding. `typeof` on an undefined variable/property returns a string which its content is "undefined".

But it's not needed to use typeof, you can directly check against `undefined`.
