### ISSUE TITLE
Banned Package Names

### ISSUE THREAD

**Issue by confused-Techie** [confused-Techie/atom-community-server-backend-JS#12]
**Is this feature Currently Implemented in any way with the upstream API Server**
- [ ] Yes
- [X] No

**Is your feature request related to a problem? Please describe.**
Prevent spam and vulgar packages.

**Describe the solution you'd like**
Some package names would be banned, disallowing them to ever be uploaded. To help reduce spam names, confusing names, or just vulgar names.

**Comment by Digitalone1** [comment]
A list of banned names could be done here. Then implemented as an array to check against the package name.

**Comment by confused-Techie** [comment]
> A list of banned names could be done here. Then implemented as an array to check against the package name.

Thanks for the suggestion. And I think you're right. I commented further on what names should be banned [here](https://github.com/confused-Techie/atom-community-server-backend-JS/issues/14), and that should be implemented as a easily configurable array within the backend.

**Comment by Digitalone1** [comment]
> Thanks for the suggestion. And I think you're right. I commented further on what names should be banned [here](https://github.com/confused-Techie/atom-community-server-backend-JS/issues/14), and that should be implemented as a easily configurable array within the backend.

Sure that list of banned packages should be compared with the strict equality.

But in order to avoid spam/vulgar names, we should have a separate list to compare with [includes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes).

**Comment by confused-Techie** [comment]
Whole-heartedly agree with you here. I've found a very simplistic package that can be used here, thats just missing some features, that I've already opened a pull request for. Feel free to take a look [here](https://github.com/coffee-and-fun/google-profanity-words) but I think it'll fit our needs nicely

**Comment by Digitalone1** [comment]
> Whole-heartedly agree with you here. I've found a very simplistic package that can be used here, thats just missing some features, that I've already opened a pull request for. Feel free to take a look [here](https://github.com/coffee-and-fun/google-profanity-words) but I think it'll fit our needs nicely

Will you import the package or it's functionality could be ported here in new functions?

**Comment by confused-Techie** [comment]
While the functionality could be ported, I think I'll import the package, to keep the overhead lower, since the codebase already is a bit large.
