### ISSUE TITLE
Verify Query Parameter Matches owner/repo

### ISSUE THREAD

**Issue by confused-Techie** [confused-Techie/atom-community-server-backend-JS#2]
In the below code, verify that 'prov' is a string in the 'owner/repo' format.
Then feel free to remove the todo.

https://github.com/confused-Techie/atom-community-server-backend-JS/blob/156ed2c85aed5f73717d945425a39a0357c9a606/src/query.js#L81-L90

**Comment by confused-Techie** [comment]
@Digitalone1 this is exactly what I was hoping for, looks great. Good move matching on beginning and end of the string too, although it may be a good idea to add period to the list of valid characters. Like `const re = new RegExp(/^[a-zA-Z0-9_\-.]+\/[a-zA-Z0-9_\-.]+$/);`. But looks fantastic

**Comment by Digitalone1** [comment]
Please, do not use `new`, javascript has a way to define regex literally.

```js
const regex = /^[[a-zA-Z0-9_\-.]+\/[[a-zA-Z0-9_.\-]+$/;
```

**Comment by confused-Techie** [comment]
Resolved by 7e365b38762bf549c1aab4c31e9baa4b9b944c75
