### ISSUE TITLE
Use `utils.LocalUserLoggedIn()`

### ISSUE THREAD

**Issue by confused-Techie** [confused-Techie/atom-community-server-backend-JS#28]
Currently there is a mix of both, a helper utility to handle user authentication, as well as handling it directly. While I love the benefit of less duplication, and less internal knowledge of authentication a helper function brings, I find the syntax very clunky and confusing.

If anyone has any thoughts on this I'd be happy to hear them, especially @Digitalone1 

The raw/standard user auth handling:

```javascript
let user = await users.VerifyAuth(params.auth);

if (!user.ok) {
  await common.AuthFail(req, res, user);
  return;
}
// code if user is logged in
```

The util function usage:

```javascript
await utils.LocalUserLoggedIn(req, res, params.auth, async () => {
  // code if user is logged in
}
```

**Comment by Digitalone1** [comment]
In my opinion the problem with `LocalUserLoggedIn` is the same as the multiple if/else statements. It introduces indentation which is not a big issue, but it's better if you can avoid it.

With `ok` property check, we can avoid the indentation after the return, but we have duplication with all those checks repeating through the code.

Maybe a solution could be:

```js
const GETStarsLogin = async (user) => {
  let packageCollection = await data.GetPackageCollection(user.content.stars);

  if (!packageCollection.ok) {
    await common.ServerError(req, res, packageCollection.content);
    return;
  }

  // We need to prune these items from a Server Package Full Item.
  let newCollection = await collection.DeepCopy(packageCollection.content);
  newCollection = await collection.POSPrune(newCollection);

  res.status(200).json(newCollection);
  logger.HTTPLog(req, res);
}

async function GETStars(req, res) {
  // GET /api/stars
  let params = {
    auth: req.get("Authorization"),
  };

  await utils.LocalUserLoggedIn(req, res, params.auth, GETStarsLogin(user));
}
```  

So `GETStarsLogin` will act as an internal util, not exported outside.

Maybe there would be a better syntax to use. I have to admit that async functions are kind of new to me. I know them from long time but never used on my site because of compatibility reasons.

**Comment by confused-Techie** [comment]
@Digitalone1 that does seem a bit easier to read. Although I'd personally vote for instead of declaring it outside the main function it can be declared inside, just to make things easier to track, like:

```javascript
async function GETStars(req, res) {
  let params = {
    auth: req.get("Authorization"),
  };

  const onLogin = async (user) => {
    let packageCollection = await data.GetPackageCollection(user.content.stars);
    // the rest of the code 
  };
  
  await utils.LocalUserLoggedIn(req, res, params.auth, onLogin(user));
}
```

Although this just reintroduces the concern of to much indentation, but I feel makes it much easier to track the logic flow. Or do you think its best to go with your suggestion, and just do our best to keep the functions close together? Because if they are seperate we also need to pass all other parameters, like the req, and res, to the callback since they loss scope

**Comment by Digitalone1** [comment]
It's up to you deciding. If you let them to stay inside, I think it's still clearer declaring the function rather than passing it directly as argument.

**Comment by confused-Techie** [comment]
So after looking at it with no real advantage other than readability, lets go with declaring the function as a variable within the handler scope. Please note that there is a syntax error in my earlier example, and the example code would have to look more like this:

```javascript
async function GETStars(req, res) {
  let params = {
    auth: req.get("Authorization"),
  };

  const onLogin = async (user) => {
    // rest of code 
  };

  await utils.LocalUserLoggedIn(req, res, params.auth, onLogin);
}
```
