### ISSUE TITLE
Database Create Scripts

### ISSUE THREAD

**Issue by confused-Techie** [confused-Techie/atom-community-server-backend-JS#39]
With the database schema defined, the next step in this process is to setup the create scripts. 

Some users here are much more familiar with SQL than I am myself, so I'm opening this up to the community for assistance.

Things to note, further details of the different tables in use are available on the [pinned discussion](https://github.com/confused-Techie/atom-community-server-backend-JS/discussions/36).
Additionally the database is running on Postgresql.

We will need create scripts for:
* [X] `names`
* [X]  `stars`
* [X]  `users`
* [X]  `packages`
* [X]  `versions`

**Comment by confused-Techie** [comment]
Modified examples from @Digitalone1 for the tables.

```sql
CREATE TABLE names (
  name VARCHAR(50) NOT NULL,
  pointer uuid NOT NULL,
  PRIMARY KEY (name),
  FOREIGN KEY (pointer) REFERENCES packages(pointer)
);

CREATE TABLE stars (
  package uuid NOT NULL,
  user INTEGER NOT NULL,
  PRIMARY KEY (package, user),
  FOREIGN KEY (package) REFERENCES packages(pointer),
  FOREIGN KEY (user) REFERENCES users(id)
);

CREATE TABLE users (
  id INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL,
  username VARCHAR(256) NOT NULL,
  token VARCHAR(256),
  avatar VARCHAR(100),
  data JSONB,
  PRIMARY KEY (id)
);

CREATE TABLE packages (
  pointer uuid NOT NULL,
  name VARCHAR(50) NOT NULL,
  created TIMESTAMP NOT NULL,
  updated TIMESTAMP,
  creation_method VARCHAR(256),
  downloads BIGINT,
  stargazers_count BIGINT,
  data JSONB,
  PRIMARY KEY (pointer)
);

CREATE TABLE versions (
  id INTEGER NOT NULL,
  package uuid NOT NULL,
  status enum,
  semver VARCHAR(256) NOT NULL,
  engine JSONB,
  license VARCHAR(256),
  meta JSONB,
  PRIMARY KEY (id),
  FOREIGN KEY (package) REFERENCES packages(pointer)
); 
```

How do we think this looks?

**Comment by Digitalone1** [comment]
Unfortunately in the last days I did not have time to do this. I will take a look at them tonight and let you know.

**Comment by confused-Techie** [comment]
> Unfortunately in the last days I did not have time to do this. I will take a look at them tonight and let you know.

No worries at all, take all the time you need and appreciate any assistance you can offer

**Comment by confused-Techie** [comment]
The only change here that I'd request at a glance is removing the `NOT NULL` directive from `users.data` and `versions.meta` since mostly with `users.data` its intended as an extra field to store data in if we need to add any additional values to a user, that doesn't have any good location to put it. But otherwise this looks fantastic, and I'll try setting this up on our server tonight. Thank you!

**Comment by confused-Techie** [comment]
@Digitalone1 Fantastic! These worked with minimal modifications (really needed to create the extension pgcrypto to use `gen_random_uuid()`) 

I've now pushed these updates to our remote server, and updated the creation scripts here 462fe118502f47eeff24441970fb9a027d3604af

Now all thats left is to migrate the existing package archive into this new table, since that was lost during this process.

But thanks for all the help with this!

**Comment by Digitalone1** [comment]
Do you need help for the migration?

**Comment by confused-Techie** [comment]
> Do you need help for the migration?

If you are willing to assist on the `INSERT` and `UPDATE` commands with the expected data within them, I can go from there, I would absolutely appreciate it

**Comment by Digitalone1** [comment]
> > Do you need help for the migration?
> 
> If you are willing to assist on the `INSERT` and `UPDATE` commands with the expected data within them, I can go from there, I would absolutely appreciate it

Which is the input data. An array of full objects?

**Comment by confused-Techie** [comment]
@Digitalone1 Sorry for such a late reply, but yes the input data would be an array of full objects, matching the archived data. Specifically refer to the data available on the [atom-package-collection](https://github.com/confused-Techie/atom-package-collection/tree/main/out) these items are what will be used to input the migrated packages into the Database.

**Comment by Digitalone1** [comment]
```js
async function database_migration(array_of_package_object_full, sql_storage) {
  await sql_storage.begin(async () => {
    const creationMethod = "Migrated from Atom DB";
    let i = 1;

    for (const p of array_of_package_object_full) {
      // Populate packages table

      const pack_data = JSON.stringify({
        "name":       p.name,
        "repository": p.repository,
        "readme":     p.readme,
        "metadata":   p.metadata
      });

      let command = await sql_storage`
        INSERT INTO packages
        (name, creation_method, data) VALUES
        (${p.name}, ${creationMethod}, ${pack_data})
        RETURNING pointer;
      `;

      const pointer = command[0].pointer;
      if (pointer === undefined) {
        throw `Cannot insert ${p.name} in packages table at iteration ${i}`;
      }

      // Populate names table
      command = await sql_storage`
        INSERT INTO names
        (name, pointer) VALUES
        (${p.name}, ${pointer});
      `;

      if (command.count === 0) {
        throw `Cannot insert ${p.name} in names table at iteration ${i}`;
      }

      // Populate versions table
      const latest = p.releases.latest;
      const pv = p.versions;

      for (const ver in pv) {
        const status = (pv.ver === latest) ? "latest" : "published";

        const engine = pv.ver.engines;
        const jsonEngine = JSON.stringify(engine);

        // Save version object into meta, but strip engines and license properties
        // since we save them in the specific separate columns
        let meta = pv.ver;
        delete meta.engines;
        delete meta.license;
        const jsonMeta = JSON.stringify(meta);

        command = await sql_storage`
          INSERT INTO versions
          (package, status, semver, license, engine, meta) VALUES
          (${pointer}, ${status}, ${ver}, ${pv.ver.license}, ${jsonEngine}, ${jsonMeta})
          RETURNING id;
        `;
      }

      if (command[0].id === undefined) {
        throw `Cannot insert ${ver} version for ${p.name} package in versions table at iteration ${i}`;
      }

      i++;
    }
  }).then((v) => {
    console.log("Atom packages successfully migrated.");
  }).catch((e) => {
    console.error(e);
    console.error("Rollback. Packages have not been migrated.");
  });
}
```

@confused-Techie Let's hope this works.

Some considerations and questions:
- `versions` table has `meta`, `engine` and `license`. I suppose meta has to store the whole version object, but is it better if we strip engine and license properties since we store them in separate columns?
- I see license is `SEE LICENSE IN LICENSE`. I think it's better if we have the exact license here. Maybe also restricting the column to `VARCHAR(32)` since only the license title is meaningful (GPL3, MIT, APACHE, etc.).
- We could restrict also `creation_method`. Maybe `VARCHAR(128)`. I don't even know what to store in this column. I made a const "Migrated from Atom DB" to not leave it as NULL. You can change it if you want.
- Am I wrong or we don't have users? Without them we can't populate the stars table also.
- Without users and stars, I suppose `downloads` and `stargazers_count` should defaults from 0?

Let me know.

**Comment by confused-Techie** [comment]
@Digitalone1 I'll happily test this out, thanks!

As for the `meta` table I was hoping to put the full object there to avoid rebuilding it when sending it to the user, which if we strip the fields it doesn't solve that problem, but if the cost of rebuilding the object is negligible, then lets save some space on our DB.

As for the `license` We could absolutely update that constraint to `VARCHAR(32)` Although for the packages that list `SEE LICENSE IN LICENSE` thats usually from an OSS application that has multiple licenses applying to it. So we may have to leave that as is unfortunately.

As for `creation_method` you're basically write there, the original terminology was slightly different, but its a way to differentiate migrated packages, and native packages.

But you are correct we have 0 users, and 0 knowledge of who has downloaded what, and who has stared what. 

I'm inclined to retain the stargazers_count and downloads count, so that we have something to build off of personally. Although I know realize this breaks the way we wanted to count stargazers unless we add an additional field of `original_stars` which may be the simplest solution, to fount both but still use our simple counting of columns later on to keep track of our stars. Then the star_gazers would be our count, plus the original stars.

But with downloads not having any reliance on anything I'd like to leave them as is. Since starting off with so many packages, it'd be nearly impossible to naturally discover anything good, especially for anyone that switches from Atom to this new backend, it may feel unfamiliar, or unused, if they just see the first page of 30 truncated packages with 0 interaction.

**Comment by Digitalone1** [comment]
So we need an additional column `original_stargazers` same type as `stargazers_count`, then we have to insert also stars and downloads into the insert query for `packages` table. You can do that easily on the script above.

**Comment by confused-Techie** [comment]
@Digitalone1 sounds fantastic to me, I'll add the `original_stargazers` column. But yeah sounds like a simple duplication from above. But I'll run this soon

**Comment by confused-Techie** [comment]
@Digitalone1 Alright, the database has been fully migrated. Due to some issues though its likely that some versions weren't able to migrate over. So we will likely need some simplistic script to verify the data that's been inputted. But otherwise, we are good to get back to actual code development.

So I'll go ahead and close this issue. Thanks for the assistance.

**Comment by Digitalone1** [comment]
> Due to some issues though its likely that some versions weren't able to migrate over. So we will likely need some simplistic script to verify the data that's been inputted. But otherwise, we are good to get back to actual code development.

Please elaborate more on that. What has gone wrong? You can always truncate all tables, fix the script and remigrate everything.

**Comment by Digitalone1** [comment]
Saw the logs you mentioned on Discord. The issue is the length of certain fields. I thought PostgreSQL would truncate them automatically. We could just specify the length in the script and truncate if it's too long.

Something like:

```js
const maxPackNameLength = 128;
const packName = p.name.substring(0, maxPackNameLength); 

command = await sql_storage`
        INSERT INTO names
        (name, pointer) VALUES
        (${packName}, ${pointer});
    `;
```

If you truncate all tables, make sure the increment value is reset: https://dba.stackexchange.com/a/193497.
